// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.proto.types;

public interface ConsensusParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.proto.types.ConsensusParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.jtendermint.jabci.proto.types.BlockParams block = 1;</code>
   */
  boolean hasBlock();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.BlockParams block = 1;</code>
   */
  com.github.jtendermint.jabci.proto.types.BlockParams getBlock();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.BlockParams block = 1;</code>
   */
  com.github.jtendermint.jabci.proto.types.BlockParamsOrBuilder getBlockOrBuilder();

  /**
   * <code>.com.github.jtendermint.jabci.proto.types.EvidenceParams evidence = 2;</code>
   */
  boolean hasEvidence();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.EvidenceParams evidence = 2;</code>
   */
  com.github.jtendermint.jabci.proto.types.EvidenceParams getEvidence();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.EvidenceParams evidence = 2;</code>
   */
  com.github.jtendermint.jabci.proto.types.EvidenceParamsOrBuilder getEvidenceOrBuilder();

  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ValidatorParams validator = 3;</code>
   */
  boolean hasValidator();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ValidatorParams validator = 3;</code>
   */
  com.github.jtendermint.jabci.proto.types.ValidatorParams getValidator();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ValidatorParams validator = 3;</code>
   */
  com.github.jtendermint.jabci.proto.types.ValidatorParamsOrBuilder getValidatorOrBuilder();
}
