// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.proto.types;

public interface ResponseInitChainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.proto.types.ResponseInitChain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ConsensusParams consensus_params = 1;</code>
   */
  boolean hasConsensusParams();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ConsensusParams consensus_params = 1;</code>
   */
  com.github.jtendermint.jabci.proto.types.ConsensusParams getConsensusParams();
  /**
   * <code>.com.github.jtendermint.jabci.proto.types.ConsensusParams consensus_params = 1;</code>
   */
  com.github.jtendermint.jabci.proto.types.ConsensusParamsOrBuilder getConsensusParamsOrBuilder();

  /**
   * <code>repeated .com.github.jtendermint.jabci.proto.types.ValidatorUpdate validators = 2;</code>
   */
  java.util.List<com.github.jtendermint.jabci.proto.types.ValidatorUpdate> 
      getValidatorsList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.proto.types.ValidatorUpdate validators = 2;</code>
   */
  com.github.jtendermint.jabci.proto.types.ValidatorUpdate getValidators(int index);
  /**
   * <code>repeated .com.github.jtendermint.jabci.proto.types.ValidatorUpdate validators = 2;</code>
   */
  int getValidatorsCount();
  /**
   * <code>repeated .com.github.jtendermint.jabci.proto.types.ValidatorUpdate validators = 2;</code>
   */
  java.util.List<? extends com.github.jtendermint.jabci.proto.types.ValidatorUpdateOrBuilder> 
      getValidatorsOrBuilderList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.proto.types.ValidatorUpdate validators = 2;</code>
   */
  com.github.jtendermint.jabci.proto.types.ValidatorUpdateOrBuilder getValidatorsOrBuilder(
      int index);
}
