// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface BlockSizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.BlockSize)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 max_bytes = 1;</code>
   */
  int getMaxBytes();

  /**
   * <code>int32 max_txs = 2;</code>
   */
  int getMaxTxs();

  /**
   * <code>int64 max_gas = 3;</code>
   */
  long getMaxGas();
}
