// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.github.jtendermint.jabci.types;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_jtendermint_jabci_types_KVPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_jtendermint_jabci_types_KVPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_jtendermint_jabci_types_KI64Pair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_jtendermint_jabci_types_KI64Pair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\"com.github.jtendermint.j" +
      "abci.types\"$\n\006KVPair\022\013\n\003key\030\001 \001(\014\022\r\n\005val" +
      "ue\030\002 \001(\014\"&\n\010KI64Pair\022\013\n\003key\030\001 \001(\014\022\r\n\005val" +
      "ue\030\002 \001(\003B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_jtendermint_jabci_types_KVPair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_jtendermint_jabci_types_KVPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_jtendermint_jabci_types_KVPair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_github_jtendermint_jabci_types_KI64Pair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_jtendermint_jabci_types_KI64Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_jtendermint_jabci_types_KI64Pair_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
