// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ConsensusParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ConsensusParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.jtendermint.jabci.types.BlockSize block_size = 1;</code>
   */
  boolean hasBlockSize();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockSize block_size = 1;</code>
   */
  com.github.jtendermint.jabci.types.BlockSize getBlockSize();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockSize block_size = 1;</code>
   */
  com.github.jtendermint.jabci.types.BlockSizeOrBuilder getBlockSizeOrBuilder();

  /**
   * <code>.com.github.jtendermint.jabci.types.TxSize tx_size = 2;</code>
   */
  boolean hasTxSize();
  /**
   * <code>.com.github.jtendermint.jabci.types.TxSize tx_size = 2;</code>
   */
  com.github.jtendermint.jabci.types.TxSize getTxSize();
  /**
   * <code>.com.github.jtendermint.jabci.types.TxSize tx_size = 2;</code>
   */
  com.github.jtendermint.jabci.types.TxSizeOrBuilder getTxSizeOrBuilder();

  /**
   * <code>.com.github.jtendermint.jabci.types.BlockGossip block_gossip = 3;</code>
   */
  boolean hasBlockGossip();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockGossip block_gossip = 3;</code>
   */
  com.github.jtendermint.jabci.types.BlockGossip getBlockGossip();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockGossip block_gossip = 3;</code>
   */
  com.github.jtendermint.jabci.types.BlockGossipOrBuilder getBlockGossipOrBuilder();
}
