// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface EvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.Evidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional .com.github.jtendermint.jabci.types.Validator validator = 2;</code>
   */
  boolean hasValidator();
  /**
   * <code>optional .com.github.jtendermint.jabci.types.Validator validator = 2;</code>
   */
  Validator getValidator();
  /**
   * <code>optional .com.github.jtendermint.jabci.types.Validator validator = 2;</code>
   */
  ValidatorOrBuilder getValidatorOrBuilder();

  /**
   * <code>optional int64 height = 3;</code>
   */
  long getHeight();

  /**
   * <code>optional int64 time = 4;</code>
   */
  long getTime();

  /**
   * <code>optional int64 total_voting_power = 5;</code>
   */
  long getTotalVotingPower();
}
