// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface LastCommitInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.LastCommitInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 round = 1;</code>
   */
  int getRound();

  /**
   * <code>repeated .com.github.jtendermint.jabci.types.VoteInfo votes = 2;</code>
   */
  java.util.List<com.github.jtendermint.jabci.types.VoteInfo> 
      getVotesList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.VoteInfo votes = 2;</code>
   */
  com.github.jtendermint.jabci.types.VoteInfo getVotes(int index);
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.VoteInfo votes = 2;</code>
   */
  int getVotesCount();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.VoteInfo votes = 2;</code>
   */
  java.util.List<? extends com.github.jtendermint.jabci.types.VoteInfoOrBuilder> 
      getVotesOrBuilderList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.VoteInfo votes = 2;</code>
   */
  com.github.jtendermint.jabci.types.VoteInfoOrBuilder getVotesOrBuilder(
      int index);
}
