// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface PartSetHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.PartSetHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 total = 1;</code>
   */
  int getTotal();

  /**
   * <code>optional bytes hash = 2;</code>
   */
  com.google.protobuf.ByteString getHash();
}
