// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface RequestBeginBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.RequestBeginBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes hash = 1;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>optional .com.github.jtendermint.jabci.types.Header header = 2;</code>
   */
  boolean hasHeader();
  /**
   * <code>optional .com.github.jtendermint.jabci.types.Header header = 2;</code>
   */
  com.github.jtendermint.jabci.types.Header getHeader();
  /**
   * <code>optional .com.github.jtendermint.jabci.types.Header header = 2;</code>
   */
  com.github.jtendermint.jabci.types.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated int32 absent_validators = 3;</code>
   */
  java.util.List<java.lang.Integer> getAbsentValidatorsList();
  /**
   * <code>repeated int32 absent_validators = 3;</code>
   */
  int getAbsentValidatorsCount();
  /**
   * <code>repeated int32 absent_validators = 3;</code>
   */
  int getAbsentValidators(int index);

  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Evidence byzantine_validators = 4;</code>
   */
  java.util.List<com.github.jtendermint.jabci.types.Evidence> 
      getByzantineValidatorsList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Evidence byzantine_validators = 4;</code>
   */
  com.github.jtendermint.jabci.types.Evidence getByzantineValidators(int index);
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Evidence byzantine_validators = 4;</code>
   */
  int getByzantineValidatorsCount();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Evidence byzantine_validators = 4;</code>
   */
  java.util.List<? extends com.github.jtendermint.jabci.types.EvidenceOrBuilder> 
      getByzantineValidatorsOrBuilderList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Evidence byzantine_validators = 4;</code>
   */
  com.github.jtendermint.jabci.types.EvidenceOrBuilder getByzantineValidatorsOrBuilder(
      int index);
}
