// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>int64 index = 2;</code>
   */
  long getIndex();

  /**
   * <pre>
   *[(gogoproto.customtype) = "github.com/tendermint/go-wire/data.Bytes", (gogoproto.nullable) = false];
   * </pre>
   *
   * <code>bytes key = 3;</code>
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <pre>
   *[(gogoproto.customtype) = "github.com/tendermint/go-wire/data.Bytes", (gogoproto.nullable) = false];
   * </pre>
   *
   * <code>bytes value = 4;</code>
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <pre>
   *[(gogoproto.customtype) = "github.com/tendermint/go-wire/data.Bytes", (gogoproto.nullable) = false];
   * </pre>
   *
   * <code>bytes proof = 5;</code>
   */
  com.google.protobuf.ByteString getProof();

  /**
   * <code>int64 height = 6;</code>
   */
  long getHeight();

  /**
   * <code>string log = 7;</code>
   */
  java.lang.String getLog();
  /**
   * <code>string log = 7;</code>
   */
  com.google.protobuf.ByteString
      getLogBytes();
}
