// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseCheckTxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseCheckTx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <pre>
   *[(gogoproto.customtype) = "github.com/tendermint/go-wire/data.Bytes", (gogoproto.nullable) = false];
   * </pre>
   *
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string log = 3;</code>
   */
  java.lang.String getLog();
  /**
   * <code>string log = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogBytes();

  /**
   * <code>int64 gas = 4;</code>
   */
  long getGas();

  /**
   * <code>int64 fee = 5;</code>
   */
  long getFee();
}
