// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseExceptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseException)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string error = 1;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
