// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>uint64 app_version = 3;</code>
   */
  long getAppVersion();

  /**
   * <code>int64 last_block_height = 4;</code>
   */
  long getLastBlockHeight();

  /**
   * <code>bytes last_block_app_hash = 5;</code>
   */
  com.google.protobuf.ByteString getLastBlockAppHash();
}
