// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseEndBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseEndBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Validator validator_updates = 1;</code>
   */
  java.util.List<com.github.jtendermint.jabci.types.Validator> 
      getValidatorUpdatesList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Validator validator_updates = 1;</code>
   */
  com.github.jtendermint.jabci.types.Validator getValidatorUpdates(int index);
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Validator validator_updates = 1;</code>
   */
  int getValidatorUpdatesCount();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Validator validator_updates = 1;</code>
   */
  java.util.List<? extends com.github.jtendermint.jabci.types.ValidatorOrBuilder> 
      getValidatorUpdatesOrBuilderList();
  /**
   * <code>repeated .com.github.jtendermint.jabci.types.Validator validator_updates = 1;</code>
   */
  com.github.jtendermint.jabci.types.ValidatorOrBuilder getValidatorUpdatesOrBuilder(
      int index);

  /**
   * <code>.com.github.jtendermint.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  boolean hasConsensusParamUpdates();
  /**
   * <code>.com.github.jtendermint.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  com.github.jtendermint.jabci.types.ConsensusParams getConsensusParamUpdates();
  /**
   * <code>.com.github.jtendermint.jabci.types.ConsensusParams consensus_param_updates = 2;</code>
   */
  com.github.jtendermint.jabci.types.ConsensusParamsOrBuilder getConsensusParamUpdatesOrBuilder();
}
