// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface ResponseCommitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.ResponseCommit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * reserve 1
   * </pre>
   *
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
