// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface VersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.Version)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 Block = 1;</code>
   */
  long getBlock();

  /**
   * <code>uint64 App = 2;</code>
   */
  long getApp();
}
