// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.types;

public interface VoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.jtendermint.jabci.types.Vote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   */
  int getType();

  /**
   * <code>int64 height = 2;</code>
   */
  long getHeight();

  /**
   * <code>int32 round = 3;</code>
   */
  int getRound();

  /**
   * <code>.com.github.jtendermint.jabci.types.BlockID block_id = 4;</code>
   */
  boolean hasBlockId();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockID block_id = 4;</code>
   */
  com.github.jtendermint.jabci.types.BlockID getBlockId();
  /**
   * <code>.com.github.jtendermint.jabci.types.BlockID block_id = 4;</code>
   */
  com.github.jtendermint.jabci.types.BlockIDOrBuilder getBlockIdOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>bytes validator_address = 6;</code>
   */
  com.google.protobuf.ByteString getValidatorAddress();

  /**
   * <code>int32 validator_index = 7;</code>
   */
  int getValidatorIndex();

  /**
   * <code>bytes signature = 8;</code>
   */
  com.google.protobuf.ByteString getSignature();
}
