// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.protobuf.types;

public interface ResponseInitChainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.ResponseInitChain)
    com.google.protobuf.MessageOrBuilder {
}
