// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.protobuf.types;

public interface ResponseDeliverTxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.ResponseDeliverTx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>bytes data = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/tendermint/go-wire/data.Bytes"];</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string log = 3;</code>
   */
  String getLog();
  /**
   * <code>string log = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogBytes();

  /**
   * <code>repeated .types.KVPair tags = 4;</code>
   */
  java.util.List<KVPair>
      getTagsList();
  /**
   * <code>repeated .types.KVPair tags = 4;</code>
   */
  KVPair getTags(int index);
  /**
   * <code>repeated .types.KVPair tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .types.KVPair tags = 4;</code>
   */
  java.util.List<? extends KVPairOrBuilder>
      getTagsOrBuilderList();
  /**
   * <code>repeated .types.KVPair tags = 4;</code>
   */
  KVPairOrBuilder getTagsOrBuilder(
      int index);
}
