// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package com.github.jtendermint.jabci.protobuf.types;

import com.github.jtendermint.jabci.protobuf.types.gogoproto.GoGoProtos;

public final class Types {
  private Types() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestEcho_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestEcho_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestFlush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestFlush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestSetOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestSetOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestInitChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestInitChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestBeginBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestBeginBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestCheckTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestCheckTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestDeliverTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestDeliverTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestEndBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestEndBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_RequestCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_RequestCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseException_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseException_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseEcho_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseEcho_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseFlush_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseFlush_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseSetOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseSetOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseInitChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseInitChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseBeginBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseBeginBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseCheckTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseCheckTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseDeliverTx_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseDeliverTx_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseEndBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseEndBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ResponseCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ResponseCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ConsensusParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ConsensusParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_BlockSize_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_BlockSize_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_TxSize_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_TxSize_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_BlockGossip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_BlockGossip_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_BlockID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_BlockID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_PartSetHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_PartSetHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Validator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Validator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_Evidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_Evidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_KVPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_KVPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013types.proto\022\005types\032\ngogo.proto\"\344\003\n\007Req" +
      "uest\022\"\n\004echo\030\002 \001(\0132\022.types.RequestEchoH\000" +
      "\022$\n\005flush\030\003 \001(\0132\023.types.RequestFlushH\000\022\"" +
      "\n\004info\030\004 \001(\0132\022.types.RequestInfoH\000\022-\n\nse" +
      "t_option\030\005 \001(\0132\027.types.RequestSetOptionH" +
      "\000\022-\n\ninit_chain\030\006 \001(\0132\027.types.RequestIni" +
      "tChainH\000\022$\n\005query\030\007 \001(\0132\023.types.RequestQ" +
      "ueryH\000\022/\n\013begin_block\030\010 \001(\0132\030.types.Requ" +
      "estBeginBlockH\000\022)\n\010check_tx\030\t \001(\0132\025.type" +
      "s.RequestCheckTxH\000\022-\n\ndeliver_tx\030\023 \001(\0132\027" +
      ".types.RequestDeliverTxH\000\022+\n\tend_block\030\013" +
      " \001(\0132\026.types.RequestEndBlockH\000\022&\n\006commit" +
      "\030\014 \001(\0132\024.types.RequestCommitH\000B\007\n\005value\"" +
      "\036\n\013RequestEcho\022\017\n\007message\030\001 \001(\t\"\016\n\014Reque" +
      "stFlush\"\036\n\013RequestInfo\022\017\n\007version\030\001 \001(\t\"" +
      ".\n\020RequestSetOption\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t\"8\n\020RequestInitChain\022$\n\nvalidator" +
      "s\030\001 \003(\0132\020.types.Validator\"I\n\014RequestQuer" +
      "y\022\014\n\004data\030\001 \001(\014\022\014\n\004path\030\002 \001(\t\022\016\n\006height\030" +
      "\003 \001(\003\022\r\n\005prove\030\004 \001(\010\"\212\001\n\021RequestBeginBlo" +
      "ck\022\014\n\004hash\030\001 \001(\014\022\035\n\006header\030\002 \001(\0132\r.types" +
      ".Header\022\031\n\021absent_validators\030\003 \003(\005\022-\n\024by" +
      "zantine_validators\030\004 \003(\0132\017.types.Evidenc" +
      "e\"\034\n\016RequestCheckTx\022\n\n\002tx\030\001 \001(\014\"\036\n\020Reque" +
      "stDeliverTx\022\n\n\002tx\030\001 \001(\014\"!\n\017RequestEndBlo" +
      "ck\022\016\n\006height\030\001 \001(\003\"\017\n\rRequestCommit\"\237\004\n\010" +
      "Response\022-\n\texception\030\001 \001(\0132\030.types.Resp" +
      "onseExceptionH\000\022#\n\004echo\030\002 \001(\0132\023.types.Re" +
      "sponseEchoH\000\022%\n\005flush\030\003 \001(\0132\024.types.Resp" +
      "onseFlushH\000\022#\n\004info\030\004 \001(\0132\023.types.Respon" +
      "seInfoH\000\022.\n\nset_option\030\005 \001(\0132\030.types.Res" +
      "ponseSetOptionH\000\022.\n\ninit_chain\030\006 \001(\0132\030.t" +
      "ypes.ResponseInitChainH\000\022%\n\005query\030\007 \001(\0132" +
      "\024.types.ResponseQueryH\000\0220\n\013begin_block\030\010" +
      " \001(\0132\031.types.ResponseBeginBlockH\000\022*\n\010che" +
      "ck_tx\030\t \001(\0132\026.types.ResponseCheckTxH\000\022.\n" +
      "\ndeliver_tx\030\n \001(\0132\030.types.ResponseDelive" +
      "rTxH\000\022,\n\tend_block\030\013 \001(\0132\027.types.Respons" +
      "eEndBlockH\000\022\'\n\006commit\030\014 \001(\0132\025.types.Resp" +
      "onseCommitH\000B\007\n\005value\"\"\n\021ResponseExcepti" +
      "on\022\r\n\005error\030\001 \001(\t\"\037\n\014ResponseEcho\022\017\n\007mes" +
      "sage\030\001 \001(\t\"\017\n\rResponseFlush\"e\n\014ResponseI" +
      "nfo\022\014\n\004data\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\031\n\021la" +
      "st_block_height\030\003 \001(\003\022\033\n\023last_block_app_" +
      "hash\030\004 \001(\014\".\n\021ResponseSetOption\022\014\n\004code\030" +
      "\001 \001(\r\022\013\n\003log\030\002 \001(\t\"\023\n\021ResponseInitChain\"" +
      "\212\002\n\rResponseQuery\022\014\n\004code\030\001 \001(\r\022\r\n\005index" +
      "\030\002 \001(\003\022=\n\003key\030\003 \001(\014B0\332\336\037(github.com/tend" +
      "ermint/go-wire/data.Bytes\310\336\037\000\022?\n\005value\030\004" +
      " \001(\014B0\332\336\037(github.com/tendermint/go-wire/" +
      "data.Bytes\310\336\037\000\022?\n\005proof\030\005 \001(\014B0\332\336\037(githu" +
      "b.com/tendermint/go-wire/data.Bytes\310\336\037\000\022" +
      "\016\n\006height\030\006 \001(\003\022\013\n\003log\030\007 \001(\t\"\024\n\022Response" +
      "BeginBlock\"\206\001\n\017ResponseCheckTx\022\014\n\004code\030\001" +
      " \001(\r\022>\n\004data\030\002 \001(\014B0\332\336\037(github.com/tende" +
      "rmint/go-wire/data.Bytes\310\336\037\000\022\013\n\003log\030\003 \001(" +
      "\t\022\013\n\003gas\030\004 \001(\003\022\013\n\003fee\030\005 \001(\003\"\213\001\n\021Response" +
      "DeliverTx\022\014\n\004code\030\001 \001(\r\022>\n\004data\030\002 \001(\014B0\332" +
      "\336\037(github.com/tendermint/go-wire/data.By" +
      "tes\310\336\037\000\022\013\n\003log\030\003 \001(\t\022\033\n\004tags\030\004 \003(\0132\r.typ" +
      "es.KVPair\"x\n\020ResponseEndBlock\022+\n\021validat" +
      "or_updates\030\001 \003(\0132\020.types.Validator\0227\n\027co" +
      "nsensus_param_updates\030\002 \001(\0132\026.types.Cons" +
      "ensusParams\"k\n\016ResponseCommit\022\014\n\004code\030\001 " +
      "\001(\r\022>\n\004data\030\002 \001(\014B0\332\336\037(github.com/tender" +
      "mint/go-wire/data.Bytes\310\336\037\000\022\013\n\003log\030\003 \001(\t" +
      "\"\201\001\n\017ConsensusParams\022$\n\nblock_size\030\001 \001(\013" +
      "2\020.types.BlockSize\022\036\n\007tx_size\030\002 \001(\0132\r.ty" +
      "pes.TxSize\022(\n\014block_gossip\030\003 \001(\0132\022.types" +
      ".BlockGossip\"@\n\tBlockSize\022\021\n\tmax_bytes\030\001" +
      " \001(\005\022\017\n\007max_txs\030\002 \001(\005\022\017\n\007max_gas\030\003 \001(\003\"," +
      "\n\006TxSize\022\021\n\tmax_bytes\030\001 \001(\005\022\017\n\007max_gas\030\002" +
      " \001(\003\",\n\013BlockGossip\022\035\n\025block_part_size_b" +
      "ytes\030\001 \001(\005\"\346\001\n\006Header\022\035\n\010chain_id\030\001 \001(\tB" +
      "\013\342\336\037\007ChainID\022\016\n\006height\030\002 \001(\003\022\014\n\004time\030\003 \001" +
      "(\003\022\017\n\007num_txs\030\004 \001(\005\0226\n\rlast_block_id\030\005 \001" +
      "(\0132\016.types.BlockIDB\017\342\336\037\013LastBlockID\022\030\n\020l" +
      "ast_commit_hash\030\006 \001(\014\022\021\n\tdata_hash\030\007 \001(\014" +
      "\022\027\n\017validators_hash\030\010 \001(\014\022\020\n\010app_hash\030\t " +
      "\001(\014\"<\n\007BlockID\022\014\n\004hash\030\001 \001(\014\022#\n\005parts\030\002 " +
      "\001(\0132\024.types.PartSetHeader\",\n\rPartSetHead" +
      "er\022\r\n\005total\030\001 \001(\005\022\014\n\004hash\030\002 \001(\014\"+\n\tValid" +
      "ator\022\017\n\007pub_key\030\001 \001(\014\022\r\n\005power\030\002 \001(\003\"+\n\010" +
      "Evidence\022\017\n\007pub_key\030\001 \001(\014\022\016\n\006height\030\002 \001(" +
      "\003\"\203\001\n\006KVPair\022\013\n\003key\030\001 \001(\t\022&\n\nvalue_type\030" +
      "\002 \001(\0162\022.types.KVPair.Type\022\024\n\014value_strin" +
      "g\030\003 \001(\t\022\021\n\tvalue_int\030\004 \001(\003\"\033\n\004Type\022\n\n\006ST" +
      "RING\020\000\022\007\n\003INT\020\0012\214\005\n\017ABCIApplication\022/\n\004E" +
      "cho\022\022.types.RequestEcho\032\023.types.Response" +
      "Echo\0222\n\005Flush\022\023.types.RequestFlush\032\024.typ" +
      "es.ResponseFlush\022/\n\004Info\022\022.types.Request" +
      "Info\032\023.types.ResponseInfo\022>\n\tSetOption\022\027" +
      ".types.RequestSetOption\032\030.types.Response" +
      "SetOption\022>\n\tDeliverTx\022\027.types.RequestDe" +
      "liverTx\032\030.types.ResponseDeliverTx\0228\n\007Che" +
      "ckTx\022\025.types.RequestCheckTx\032\026.types.Resp" +
      "onseCheckTx\0222\n\005Query\022\023.types.RequestQuer" +
      "y\032\024.types.ResponseQuery\0225\n\006Commit\022\024.type" +
      "s.RequestCommit\032\025.types.ResponseCommit\022>" +
      "\n\tInitChain\022\027.types.RequestInitChain\032\030.t" +
      "ypes.ResponseInitChain\022A\n\nBeginBlock\022\030.t" +
      "ypes.RequestBeginBlock\032\031.types.ResponseB" +
      "eginBlock\022;\n\010EndBlock\022\026.types.RequestEnd" +
      "Block\032\027.types.ResponseEndBlockB/\n+com.gi" +
      "thub.jtendermint.jabci.protobuf.typesP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_types_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Request_descriptor,
        new String[] { "Echo", "Flush", "Info", "SetOption", "InitChain", "Query", "BeginBlock", "CheckTx", "DeliverTx", "EndBlock", "Commit", "Value", });
    internal_static_types_RequestEcho_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_types_RequestEcho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestEcho_descriptor,
        new String[] { "Message", });
    internal_static_types_RequestFlush_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_types_RequestFlush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestFlush_descriptor,
        new String[] { });
    internal_static_types_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_types_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestInfo_descriptor,
        new String[] { "Version", });
    internal_static_types_RequestSetOption_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_types_RequestSetOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestSetOption_descriptor,
        new String[] { "Key", "Value", });
    internal_static_types_RequestInitChain_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_types_RequestInitChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestInitChain_descriptor,
        new String[] { "Validators", });
    internal_static_types_RequestQuery_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_types_RequestQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestQuery_descriptor,
        new String[] { "Data", "Path", "Height", "Prove", });
    internal_static_types_RequestBeginBlock_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_types_RequestBeginBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestBeginBlock_descriptor,
        new String[] { "Hash", "Header", "AbsentValidators", "ByzantineValidators", });
    internal_static_types_RequestCheckTx_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_types_RequestCheckTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestCheckTx_descriptor,
        new String[] { "Tx", });
    internal_static_types_RequestDeliverTx_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_types_RequestDeliverTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestDeliverTx_descriptor,
        new String[] { "Tx", });
    internal_static_types_RequestEndBlock_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_types_RequestEndBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestEndBlock_descriptor,
        new String[] { "Height", });
    internal_static_types_RequestCommit_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_types_RequestCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_RequestCommit_descriptor,
        new String[] { });
    internal_static_types_Response_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_types_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Response_descriptor,
        new String[] { "Exception", "Echo", "Flush", "Info", "SetOption", "InitChain", "Query", "BeginBlock", "CheckTx", "DeliverTx", "EndBlock", "Commit", "Value", });
    internal_static_types_ResponseException_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_types_ResponseException_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseException_descriptor,
        new String[] { "Error", });
    internal_static_types_ResponseEcho_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_types_ResponseEcho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseEcho_descriptor,
        new String[] { "Message", });
    internal_static_types_ResponseFlush_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_types_ResponseFlush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseFlush_descriptor,
        new String[] { });
    internal_static_types_ResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_types_ResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseInfo_descriptor,
        new String[] { "Data", "Version", "LastBlockHeight", "LastBlockAppHash", });
    internal_static_types_ResponseSetOption_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_types_ResponseSetOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseSetOption_descriptor,
        new String[] { "Code", "Log", });
    internal_static_types_ResponseInitChain_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_types_ResponseInitChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseInitChain_descriptor,
        new String[] { });
    internal_static_types_ResponseQuery_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_types_ResponseQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseQuery_descriptor,
        new String[] { "Code", "Index", "Key", "Value", "Proof", "Height", "Log", });
    internal_static_types_ResponseBeginBlock_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_types_ResponseBeginBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseBeginBlock_descriptor,
        new String[] { });
    internal_static_types_ResponseCheckTx_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_types_ResponseCheckTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseCheckTx_descriptor,
        new String[] { "Code", "Data", "Log", "Gas", "Fee", });
    internal_static_types_ResponseDeliverTx_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_types_ResponseDeliverTx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseDeliverTx_descriptor,
        new String[] { "Code", "Data", "Log", "Tags", });
    internal_static_types_ResponseEndBlock_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_types_ResponseEndBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseEndBlock_descriptor,
        new String[] { "ValidatorUpdates", "ConsensusParamUpdates", });
    internal_static_types_ResponseCommit_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_types_ResponseCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ResponseCommit_descriptor,
        new String[] { "Code", "Data", "Log", });
    internal_static_types_ConsensusParams_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_types_ConsensusParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ConsensusParams_descriptor,
        new String[] { "BlockSize", "TxSize", "BlockGossip", });
    internal_static_types_BlockSize_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_types_BlockSize_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_BlockSize_descriptor,
        new String[] { "MaxBytes", "MaxTxs", "MaxGas", });
    internal_static_types_TxSize_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_types_TxSize_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_TxSize_descriptor,
        new String[] { "MaxBytes", "MaxGas", });
    internal_static_types_BlockGossip_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_types_BlockGossip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_BlockGossip_descriptor,
        new String[] { "BlockPartSizeBytes", });
    internal_static_types_Header_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_types_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Header_descriptor,
        new String[] { "ChainId", "Height", "Time", "NumTxs", "LastBlockId", "LastCommitHash", "DataHash", "ValidatorsHash", "AppHash", });
    internal_static_types_BlockID_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_types_BlockID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_BlockID_descriptor,
        new String[] { "Hash", "Parts", });
    internal_static_types_PartSetHeader_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_types_PartSetHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_PartSetHeader_descriptor,
        new String[] { "Total", "Hash", });
    internal_static_types_Validator_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_types_Validator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Validator_descriptor,
        new String[] { "PubKey", "Power", });
    internal_static_types_Evidence_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_types_Evidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_Evidence_descriptor,
        new String[] { "PubKey", "Height", });
    internal_static_types_KVPair_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_types_KVPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_KVPair_descriptor,
        new String[] { "Key", "ValueType", "ValueString", "ValueInt", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(GoGoProtos.customname);
    registry.add(GoGoProtos.customtype);
    registry.add(GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
